# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Restaurant.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 632)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/images2.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 10, 791, 621))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.manager_names_comboBox = QtWidgets.QComboBox(self.page)
        self.manager_names_comboBox.setGeometry(QtCore.QRect(20, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.manager_names_comboBox.setFont(font)
        self.manager_names_comboBox.setObjectName("manager_names_comboBox")
        self.manager_names_label = QtWidgets.QLabel(self.page)
        self.manager_names_label.setGeometry(QtCore.QRect(30, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        font.setItalic(True)
        self.manager_names_label.setFont(font)
        self.manager_names_label.setObjectName("manager_names_label")
        self.dateEdit = QtWidgets.QDateEdit(self.page)
        self.dateEdit.setGeometry(QtCore.QRect(480, 70, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.date_label = QtWidgets.QLabel(self.page)
        self.date_label.setGeometry(QtCore.QRect(490, 40, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.timeEdit = QtWidgets.QTimeEdit(self.page)
        self.timeEdit.setGeometry(QtCore.QRect(630, 70, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.timeEdit.setFont(font)
        self.timeEdit.setObjectName("timeEdit")
        self.time_label = QtWidgets.QLabel(self.page)
        self.time_label.setGeometry(QtCore.QRect(630, 40, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.menu_comboBox = QtWidgets.QComboBox(self.page)
        self.menu_comboBox.setGeometry(QtCore.QRect(30, 240, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.menu_comboBox.setFont(font)
        self.menu_comboBox.setObjectName("menu_comboBox")
        self.analysis_pushButton = QtWidgets.QPushButton(self.page)
        self.analysis_pushButton.setGeometry(QtCore.QRect(490, 510, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.analysis_pushButton.setFont(font)
        self.analysis_pushButton.setAutoFillBackground(False)
        self.analysis_pushButton.setObjectName("analysis_pushButton")
        self.menu_label = QtWidgets.QLabel(self.page)
        self.menu_label.setGeometry(QtCore.QRect(200, 160, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        font.setItalic(True)
        self.menu_label.setFont(font)
        self.menu_label.setObjectName("menu_label")
        self.amount_label = QtWidgets.QLabel(self.page)
        self.amount_label.setGeometry(QtCore.QRect(450, 200, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.amount_label.setFont(font)
        self.amount_label.setAutoFillBackground(False)
        self.amount_label.setObjectName("amount_label")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(220, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.total_label = QtWidgets.QLabel(self.page)
        self.total_label.setGeometry(QtCore.QRect(10, 490, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.total_label.setFont(font)
        self.total_label.setObjectName("total_label")
        self.delete_comboBox = QtWidgets.QComboBox(self.page)
        self.delete_comboBox.setGeometry(QtCore.QRect(40, 400, 331, 22))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.delete_comboBox.setFont(font)
        self.delete_comboBox.setObjectName("delete_comboBox")
        self.delete_label = QtWidgets.QLabel(self.page)
        self.delete_label.setGeometry(QtCore.QRect(136, 370, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        font.setItalic(True)
        self.delete_label.setFont(font)
        self.delete_label.setObjectName("delete_label")
        self.bill_pushButton = QtWidgets.QPushButton(self.page)
        self.bill_pushButton.setGeometry(QtCore.QRect(100, 520, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_pushButton.setFont(font)
        self.bill_pushButton.setObjectName("bill_pushButton")
        self.add_pushButton = QtWidgets.QPushButton(self.page)
        self.add_pushButton.setGeometry(QtCore.QRect(180, 290, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.add_pushButton.setFont(font)
        self.add_pushButton.setObjectName("add_pushButton")
        self.delete_pushButton = QtWidgets.QPushButton(self.page)
        self.delete_pushButton.setGeometry(QtCore.QRect(160, 440, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.delete_pushButton.setFont(font)
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.amount_label_2 = QtWidgets.QLabel(self.page)
        self.amount_label_2.setGeometry(QtCore.QRect(400, 380, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.amount_label_2.setFont(font)
        self.amount_label_2.setObjectName("amount_label_2")
        self.amount_spinBox_2 = QtWidgets.QSpinBox(self.page)
        self.amount_spinBox_2.setGeometry(QtCore.QRect(410, 410, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.amount_spinBox_2.setFont(font)
        self.amount_spinBox_2.setProperty("value", 1)
        self.amount_spinBox_2.setObjectName("amount_spinBox_2")
        self.amount_spinBox = QtWidgets.QSpinBox(self.page)
        self.amount_spinBox.setGeometry(QtCore.QRect(460, 240, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.amount_spinBox.setFont(font)
        self.amount_spinBox.setProperty("value", 1)
        self.amount_spinBox.setObjectName("amount_spinBox")
        self.appetizer_pushButton = QtWidgets.QPushButton(self.page)
        self.appetizer_pushButton.setGeometry(QtCore.QRect(40, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.appetizer_pushButton.setFont(font)
        self.appetizer_pushButton.setObjectName("appetizer_pushButton")
        self.maincourse_pushButton = QtWidgets.QPushButton(self.page)
        self.maincourse_pushButton.setGeometry(QtCore.QRect(160, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.maincourse_pushButton.setFont(font)
        self.maincourse_pushButton.setObjectName("maincourse_pushButton")
        self.beverage_pushButton = QtWidgets.QPushButton(self.page)
        self.beverage_pushButton.setGeometry(QtCore.QRect(290, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.beverage_pushButton.setFont(font)
        self.beverage_pushButton.setObjectName("beverage_pushButton")
        self.refresh_pushButton = QtWidgets.QPushButton(self.page)
        self.refresh_pushButton.setGeometry(QtCore.QRect(270, 90, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.refresh_pushButton.setFont(font)
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.reset_pushButton = QtWidgets.QPushButton(self.page)
        self.reset_pushButton.setGeometry(QtCore.QRect(310, 520, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.reset_pushButton.setFont(font)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.week_graph = QtWidgets.QLabel(self.page_2)
        self.week_graph.setGeometry(QtCore.QRect(0, -40, 571, 301))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.week_graph.setFont(font)
        self.week_graph.setStyleSheet("image: url(:/newPrefix/Graphs/NoData.png);")
        self.week_graph.setText("")
        self.week_graph.setScaledContents(True)
        self.week_graph.setObjectName("week_graph")
        self.data_back_pushButton = QtWidgets.QPushButton(self.page_2)
        self.data_back_pushButton.setGeometry(QtCore.QRect(600, 210, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.data_back_pushButton.setFont(font)
        self.data_back_pushButton.setObjectName("data_back_pushButton")
        self.mon_graph = QtWidgets.QLabel(self.page_2)
        self.mon_graph.setGeometry(QtCore.QRect(30, 270, 171, 161))
        self.mon_graph.setStyleSheet("image: url(:/newPrefix/Graphs/NoData.png);")
        self.mon_graph.setText("")
        self.mon_graph.setScaledContents(True)
        self.mon_graph.setObjectName("mon_graph")
        self.tue_graph = QtWidgets.QLabel(self.page_2)
        self.tue_graph.setGeometry(QtCore.QRect(180, 270, 161, 151))
        self.tue_graph.setStyleSheet("image: url(:/newPrefix/Graphs/NoData.png);")
        self.tue_graph.setText("")
        self.tue_graph.setScaledContents(True)
        self.tue_graph.setObjectName("tue_graph")
        self.wed_graph = QtWidgets.QLabel(self.page_2)
        self.wed_graph.setGeometry(QtCore.QRect(340, 270, 171, 161))
        self.wed_graph.setStyleSheet("image: url(:/newPrefix/Graphs/NoData.png);")
        self.wed_graph.setText("")
        self.wed_graph.setScaledContents(True)
        self.wed_graph.setObjectName("wed_graph")
        self.thu_graph = QtWidgets.QLabel(self.page_2)
        self.thu_graph.setGeometry(QtCore.QRect(500, 270, 171, 171))
        self.thu_graph.setStyleSheet("image: url(:/newPrefix/Graphs/NoData.png);")
        self.thu_graph.setText("")
        self.thu_graph.setScaledContents(True)
        self.thu_graph.setObjectName("thu_graph")
        self.fri_graph = QtWidgets.QLabel(self.page_2)
        self.fri_graph.setGeometry(QtCore.QRect(50, 430, 171, 171))
        self.fri_graph.setStyleSheet("image: url(:/newPrefix/Graphs/NoData.png);")
        self.fri_graph.setText("")
        self.fri_graph.setScaledContents(True)
        self.fri_graph.setObjectName("fri_graph")
        self.sun_graph = QtWidgets.QLabel(self.page_2)
        self.sun_graph.setGeometry(QtCore.QRect(450, 430, 171, 171))
        self.sun_graph.setStyleSheet("image: url(:/newPrefix/Graphs/NoData.png);")
        self.sun_graph.setText("")
        self.sun_graph.setScaledContents(True)
        self.sun_graph.setObjectName("sun_graph")
        self.sat_graph = QtWidgets.QLabel(self.page_2)
        self.sat_graph.setGeometry(QtCore.QRect(250, 430, 171, 171))
        self.sat_graph.setStyleSheet("image: url(:/newPrefix/Graphs/NoData.png);")
        self.sat_graph.setText("")
        self.sat_graph.setScaledContents(True)
        self.sat_graph.setObjectName("sat_graph")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(10, 410, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(170, 420, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(350, 420, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(476, 420, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(20, 590, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(240, 590, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(430, 590, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tableWidget = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget.setGeometry(QtCore.QRect(130, 110, 481, 151))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.tableWidget.setFont(font)
        self.tableWidget.setLineWidth(2)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.bill_back_pushButton = QtWidgets.QPushButton(self.page_3)
        self.bill_back_pushButton.setGeometry(QtCore.QRect(160, 520, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_back_pushButton.setFont(font)
        self.bill_back_pushButton.setObjectName("bill_back_pushButton")
        self.bill_total_label = QtWidgets.QLabel(self.page_3)
        self.bill_total_label.setGeometry(QtCore.QRect(350, 360, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_total_label.setFont(font)
        self.bill_total_label.setObjectName("bill_total_label")
        self.bill_done_pushButton = QtWidgets.QPushButton(self.page_3)
        self.bill_done_pushButton.setGeometry(QtCore.QRect(460, 510, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_done_pushButton.setFont(font)
        self.bill_done_pushButton.setObjectName("bill_done_pushButton")
        self.bill_date_label = QtWidgets.QLabel(self.page_3)
        self.bill_date_label.setGeometry(QtCore.QRect(130, 80, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_date_label.setFont(font)
        self.bill_date_label.setObjectName("bill_date_label")
        self.bill_time_label = QtWidgets.QLabel(self.page_3)
        self.bill_time_label.setGeometry(QtCore.QRect(390, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_time_label.setFont(font)
        self.bill_time_label.setObjectName("bill_time_label")
        self.bill_customer_label = QtWidgets.QLabel(self.page_3)
        self.bill_customer_label.setGeometry(QtCore.QRect(50, 40, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_customer_label.setFont(font)
        self.bill_customer_label.setObjectName("bill_customer_label")
        self.bill_mail_lineEdit = QtWidgets.QLineEdit(self.page_3)
        self.bill_mail_lineEdit.setGeometry(QtCore.QRect(50, 410, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setItalic(True)
        self.bill_mail_lineEdit.setFont(font)
        self.bill_mail_lineEdit.setObjectName("bill_mail_lineEdit")
        self.bill_mail_pushButton = QtWidgets.QPushButton(self.page_3)
        self.bill_mail_pushButton.setGeometry(QtCore.QRect(510, 410, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_mail_pushButton.setFont(font)
        self.bill_mail_pushButton.setObjectName("bill_mail_pushButton")
        self.bill_mail_label = QtWidgets.QLabel(self.page_3)
        self.bill_mail_label.setGeometry(QtCore.QRect(180, 450, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_mail_label.setFont(font)
        self.bill_mail_label.setText("")
        self.bill_mail_label.setObjectName("bill_mail_label")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(50, 380, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(9)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.bill_sub_total_label = QtWidgets.QLabel(self.page_3)
        self.bill_sub_total_label.setGeometry(QtCore.QRect(350, 270, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_sub_total_label.setFont(font)
        self.bill_sub_total_label.setObjectName("bill_sub_total_label")
        self.bill_cgst_total_label = QtWidgets.QLabel(self.page_3)
        self.bill_cgst_total_label.setGeometry(QtCore.QRect(350, 300, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_cgst_total_label.setFont(font)
        self.bill_cgst_total_label.setObjectName("bill_cgst_total_label")
        self.bill_sgst_total_label = QtWidgets.QLabel(self.page_3)
        self.bill_sgst_total_label.setGeometry(QtCore.QRect(350, 330, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        font.setItalic(True)
        self.bill_sgst_total_label.setFont(font)
        self.bill_sgst_total_label.setObjectName("bill_sgst_total_label")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.manager_names_label.setText(_translate("MainWindow", "Manager"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.time_label.setText(_translate("MainWindow", "Time"))
        self.analysis_pushButton.setText(_translate("MainWindow", "DataAnalysis"))
        self.menu_label.setText(_translate("MainWindow", "Menu"))
        self.amount_label.setText(_translate("MainWindow", "Amount"))
        self.label_3.setText(_translate("MainWindow", "MSSRS Restaurant"))
        self.total_label.setText(_translate("MainWindow", "Total Items=0"))
        self.delete_label.setText(_translate("MainWindow", " Items Ordered"))
        self.bill_pushButton.setText(_translate("MainWindow", "Bill"))
        self.add_pushButton.setText(_translate("MainWindow", "Add"))
        self.delete_pushButton.setText(_translate("MainWindow", "Delete"))
        self.amount_label_2.setText(_translate("MainWindow", "Amount"))
        self.appetizer_pushButton.setText(_translate("MainWindow", "Appetizer"))
        self.maincourse_pushButton.setText(_translate("MainWindow", "MainCourse"))
        self.beverage_pushButton.setText(_translate("MainWindow", "Beverage"))
        self.refresh_pushButton.setText(_translate("MainWindow", "Refresh"))
        self.reset_pushButton.setText(_translate("MainWindow", "Reset page"))
        self.data_back_pushButton.setText(_translate("MainWindow", "Back"))
        self.label.setText(_translate("MainWindow", "Monday"))
        self.label_2.setText(_translate("MainWindow", "Tuesday"))
        self.label_4.setText(_translate("MainWindow", "Wednesday"))
        self.label_5.setText(_translate("MainWindow", "Thursday"))
        self.label_6.setText(_translate("MainWindow", "Friday"))
        self.label_7.setText(_translate("MainWindow", "Saturday"))
        self.label_8.setText(_translate("MainWindow", "Sunday"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Dish Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Per Price"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total Price"))
        self.bill_back_pushButton.setText(_translate("MainWindow", "Back"))
        self.bill_total_label.setText(_translate("MainWindow", "Grand Total = 0"))
        self.bill_done_pushButton.setText(_translate("MainWindow", "Done"))
        self.bill_date_label.setText(_translate("MainWindow", "Date ="))
        self.bill_time_label.setText(_translate("MainWindow", "Time ="))
        self.bill_customer_label.setText(_translate("MainWindow", "Customer_id = "))
        self.bill_mail_pushButton.setText(_translate("MainWindow", "Send"))
        self.label_9.setText(_translate("MainWindow", "Email ID:"))
        self.bill_sub_total_label.setText(_translate("MainWindow", "Sub Total = 0"))
        self.bill_cgst_total_label.setText(_translate("MainWindow", "CGST (2.5%) = 0"))
        self.bill_sgst_total_label.setText(_translate("MainWindow", "SGST (2.5%) = 0"))

import xyz_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

